#RetroDevStudio.MetaData.BASIC:2049,BASIC V2,uppercase,10,10
#OK CTRL LETTERS AND DIGITS (NO M)
10PRINT"{CTRL-A}{CTRL-B}{CTRL-C}{CTRL-D}{WHITE}{CTRL-F}{CTRL-G}{CTRL-H}{CTRL-I}{CTRL-J}{CTRL-K}{CTRL-L}{CTRL-N}{CTRL-O}{CTRL-P}{DOWN}{RVSON}{HOME}{DEL}{CTRL-U}{CTRL-V}{CTRL-W}{CTRL-X}{CTRL-Y}{CTRL-Z}{BLACK}{WHITE}{RED}{CYAN}{PURPLE}{GREEN}{BLUE}{YELLOW}{RVSON}{RVSOFF}"
#OK LETTERS, DIGITS, OTHER KEYS
20PRINT"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789{ARROW LEFT}{ARROW UP}+-@*:;=,./"
#OK LETTERS, DIGITS, OTHER KEYS SHIFTED (NO SHIFT-2)
30PRINT"{SHIFT-A}{SHIFT-B}{SHIFT-C}{SHIFT-D}{SHIFT-E}{SHIFT-F}{SHIFT-G}{SHIFT-H}{SHIFT-I}{SHIFT-J}{SHIFT-K}{SHIFT-L}{SHIFT-M}{SHIFT-N}{SHIFT-O}{SHIFT-P}{SHIFT-Q}{SHIFT-R}{SHIFT-S}{SHIFT-T}{SHIFT-U}{SHIFT-V}{SHIFT-W}{SHIFT-X}{SHIFT-Y}{SHIFT-Z}0! #$%&'(){ARROW LEFT}{PI}{SHIFT-+}{SHIFT--}{SHIFT-@}{SHIFT-*}[]=<>?"
#NOK! LETTERS, DIGITS, OTHER KEYS COMMODORE (NO SHIFT-2)
40PRINT"{CBM-A}{CBM-B}{CBM-C}{CBM-D}{CBM-E}{CBM-F}{CBM-G}{CBM-H}{CBM-I}{CBM-J}{CBM-K}{CBM-L}{CBM-M}{CBM-N}{CBM-O}{CBM-P}{CBM-Q}{CBM-R}{CBM-S}{CBM-T}{CBM-U}{CBM-V}{CBM-W}{CBM-X}{CBM-Y}{CBM-Z}0{ORANGE}{BROWN}{LIGHT RED}{GREY 1}{GREY 2}{LIGHT GREEN}{LIGHT BLUE}{GREY 3}9{ARROW LEFT}{PI}{CBM-+}{CBM--}{CBM-@}{CBM-*}:;=,./"
#OK OTHER KEYS
50PRINT"{F1}{F2}{F3}{F4}{F5}{F6}{F7}{F8}{RIGHT}{DOWN}{LEFT}{UP}"