#RetroDevStudio.MetaData.BASIC:2049,BASIC V2,uppercase,10,10
10PRINT"ICH BIN EINE LANGE ZEILE UND PASSE GENAU IN DIE 80 ZEICHEN REIN!!!!!!!!"
15PRINT"ICH BIN EINE LANGE ZEILE UND PASSE GENAU IN DIE 80 ZEICHEN REIN!!!!!!!!!"
20PRINT:PRINT:PRINT:PRINT:PRINT:PRINT:PRINT:PRINT:PRINT:PRINT:PRINT:PRINT:PRINT:PRINT