#RetroDevStudio.MetaData.BASIC:2049,BASIC V2,lowercase,10,10
# *** DEFS ***
GOSUB LABEL30

END 

#INCLUDE "LABELMODEWITHINCLUDE2.BAS"
# *** UEBERSCHRIFT ***

LABEL30 
PRINTCHR$(147);
PRINT"WERT"  
RETURN 