10?"HALLO, PRESS G TO WIN"
20GETA$:IFA$=""THEN20
30IFA$="G"THEN50
40?"ENDE":END
50?"YOU WIN!"

400 P=(A$="{RIGHT}")*-1+(A$="{LEFT}")

410PRINT"{ARROW UP}{RIGHT}{RIGHT}{RIGHT}{RIGHT}{RVSON}{CYAN}      NOT A SPACE !!!           {RVSOFF}{ARROW UP}{ARROW LEFT}"