#RetroDevStudio.MetaData.BASIC:2049,BASIC V2,uppercase,10,10
LABEL10
?"HALLO, PRESS G TO WIN"

LABEL20
GETA$:IFA$=""THEN LABEL20

LABEL30
IFA$="G"THEN LABEL50
?"ENDE":END

LABEL50
?"YOU WIN!"
P=(A$="")*-1+(A$="")
PRINT"      NOT A SPACE !!!           "
ONXGOSUBLABEL10,LABEL20,LABEL30

LABEL90
IFA=1THEN LABEL90
