#RetroDevStudio.MetaData.BASIC:2049,BASIC V2,uppercase,10,10
# TEST @C64STUDIO @@@@@AAAAABBBBB@@@@@CCCCCDDDDDEEEEE

1 PRINT"@@@AAA@@DDD@CCC@@@AA@B@@C@@@"
2 PRINT"@@AAA@@DDD@CCC@@@AA@B@@C@@@A"
3 PRINT"@AAA@@DDD@CCC@@@AA@B@@C@@@AB"
4 PRINT"AAA@@DDD@CCC@@@AA@B@@C@@@ABC"
5 PRINT"AA--DDD-CCC---AAA--C---AAAAA"
