5 REM L BASIC M E P 7
10 INPUT "SKILL LEVEL (1,2 OR 3)";I
20 ON I RESTORE EL,ML,HL
30 READ A$
40 PRINT "LOADING ";A$;"...."
50 READ B$
60 LOAD B$,8,1
70 LABEL EL:DATA "EASY LEVEL" , "LEVEL 1"
80 LABEL ML:DATA "MEDIUM LEVEL" , "LEVEL 2"
90 LABEL HL:DATA "HARD LEVEL" , "LEVEL 3"