#RetroDevStudio.MetaData.BASIC:2049,BASIC V2
GOSUBLABEL1000
GOSUBLABEL500
X=5
PRINT"END OF MAIN":END

#INCLUDE "DISPLAY.BAS"

LABEL1000
PRINT"";
PRINT"THIS IS THE TITLE SCREEN"
PRINT"PRESS ANY KEY TO CONTINUE"

LABEL1030
GETA$:IFA$=""THEN LABEL1030
PRINTX
RETURN
   