namespace Tiny64
{
  public enum PhysicalKey
  {
    NONE                      = -1,
    KEY_ARROW_LEFT            = ( ( 7 << 3 ) | 1 ),
    KEY_1                     = ( ( 7 << 3 ) | 0 ),
    KEY_2                     = ( ( 7 << 3 ) | 3 ),
    KEY_3                     = ( ( 1 << 3 ) | 0 ),
    KEY_4                     = ( ( 1 << 3 ) | 3 ),
    KEY_5                     = ( ( 2 << 3 ) | 0 ),
    KEY_6                     = ( ( 2 << 3 ) | 3 ),
    KEY_7                     = ( ( 3 << 3 ) | 0 ),
    KEY_8                     = ( ( 3 << 3 ) | 3 ),
    KEY_9                     = ( ( 4 << 3 ) | 0 ),
    KEY_0                     = ( ( 4 << 3 ) | 3 ),
    KEY_PLUS                  = ( ( 5 << 3 ) | 0 ),
    KEY_MINUS                 = ( ( 5 << 3 ) | 3 ),
    KEY_POUND                 = ( ( 6 << 3 ) | 0 ),
    KEY_CLR_HOME              = ( ( 6 << 3 ) | 3 ),
    KEY_INST_DEL              = ( ( 0 << 3 ) | 0 ),
    KEY_CTRL                  = ( ( 7 << 3 ) | 2 ),
    KEY_Q                     = ( ( 7 << 3 ) | 6 ),
    KEY_W                     = ( ( 1 << 3 ) | 1 ),
    KEY_E                     = ( ( 1 << 3 ) | 6 ),
    KEY_R                     = ( ( 2 << 3 ) | 1 ),
    KEY_T                     = ( ( 2 << 3 ) | 6 ),
    KEY_Y                     = ( ( 3 << 3 ) | 1 ),
    KEY_U                     = ( ( 3 << 3 ) | 6 ),
    KEY_I                     = ( ( 4 << 3 ) | 1 ),
    KEY_O                     = ( ( 4 << 3 ) | 6 ),
    KEY_P                     = ( ( 5 << 3 ) | 1 ),
    KEY_AT                    = ( ( 5 << 3 ) | 6 ),
    KEY_STAR                  = ( ( 6 << 3 ) | 1 ),
    KEY_ARROW_UP              = ( ( 6 << 3 ) | 6 ),
    KEY_RESTORE               = 64,  
    KEY_RUN_STOP              = ( ( 7 << 3 ) | 7 ),
    KEY_SHIFT_LOCK            = 65,
    KEY_A                     = ( ( 1 << 3 ) | 2 ),
    KEY_S                     = ( ( 1 << 3 ) | 5 ),
    KEY_D                     = ( ( 2 << 3 ) | 2 ),
    KEY_F                     = ( ( 2 << 3 ) | 5 ),
    KEY_G                     = ( ( 3 << 3 ) | 2 ),
    KEY_H                     = ( ( 3 << 3 ) | 5 ),
    KEY_J                     = ( ( 4 << 3 ) | 2 ),
    KEY_K                     = ( ( 4 << 3 ) | 5 ),
    KEY_L                     = ( ( 5 << 3 ) | 2 ),
    KEY_COLON                 = ( ( 5 << 3 ) | 5 ),
    KEY_SEMI_COLON            = ( ( 6 << 3 ) | 2 ),
    KEY_EQUAL                 = ( ( 6 << 3 ) | 5 ),
    KEY_RETURN                = ( ( 0 << 3 ) | 1 ),
    KEY_COMMODORE             = ( ( 7 << 3 ) | 5 ),
    KEY_SHIFT_LEFT            = ( ( 1 << 3 ) | 7 ),
    KEY_Z                     = ( ( 1 << 3 ) | 4 ),
    KEY_X                     = ( ( 2 << 3 ) | 7 ),
    KEY_C                     = ( ( 2 << 3 ) | 4 ),
    KEY_V                     = ( ( 3 << 3 ) | 7 ),
    KEY_B                     = ( ( 3 << 3 ) | 4 ),
    KEY_N                     = ( ( 4 << 3 ) | 7 ),
    KEY_M                     = ( ( 4 << 3 ) | 4 ),
    KEY_COMMA                 = ( ( 5 << 3 ) | 7 ),
    KEY_DOT                   = ( ( 5 << 3 ) | 4 ),
    KEY_SLASH                 = ( ( 6 << 3 ) | 7 ),
    KEY_SHIFT_RIGHT           = ( ( 6 << 3 ) | 4 ),
    KEY_CURSOR_UP_DOWN        = ( ( 0 << 3 ) | 7 ),
    KEY_CURSOR_LEFT_RIGHT     = ( ( 0 << 3 ) | 2 ),
    KEY_SPACE                 = ( ( 7 << 3 ) | 4 ),
    KEY_F1                    = ( ( 0 << 3 ) | 4 ),
    KEY_F3                    = ( ( 0 << 3 ) | 5 ),
    KEY_F5                    = ( ( 0 << 3 ) | 6 ),
    KEY_F7                    = ( ( 0 << 3 ) | 3 )
  }


}
