#RetroDevStudio.MetaData.BASIC:2049,BASIC V2,uppercase,10,10
10IFA=0THENA=1:LOAD"ASM",8,1

20?"{CLR}"


# INSERT THE VALUE OF ASSEMBLY LABEL ASM_START
30SYS{ASM_START}


# INSERT THE VALUE OF ANOTHERLABEL
40?"LABEL HAS THE VALUE OF {ANOTHERLABEL}"


# HEX LITERALS ARE CONVERTED TO DECIMAL

50?"THIS SHOULD SHOW 49152 HERE: {$C000}"


# INSERT THE VALUE OF ANOTHERLABEL
100X={ANOTHERLABEL}
110PRINT"X="X


# MAIN MENU
1000PRINT"WELCOME TO MY SAMPLE"
1010GETA$:IFA$=""THEN1010
