#C64Studio.MetaData.BASIC:2049,BASIC V2
10 PRINT"";
20 POKE53280,0:POKE53281,0
30 PRINT"                            ";
40 PRINT"                             ";
50 PRINT"                       ";
60 PRINT"                             ";
70 PRINT"                             ";
80 PRINT"                      ";
90 PRINT"                             ";
100 PRINT"                            ";
110 PRINT"                       ";
120 PRINT"                            ";
130 PRINT"                            ";
140 PRINT"                        ";
150 PRINT"                            ";
160 PRINT"                            ";
170 PRINT"                        ";
180 PRINT"                            ";
190 PRINT"                            ";
200 PRINT"                        ";
210 PRINT"                        ";
220 PRINT"               ";
230 PRINT"                    ";
240 PRINT"             ";
250 PRINT"                       ";
260 PRINT"               ";
270 PRINT"                     ";
280 PRINT"                 ";
290 PRINT"                        ";
300 PRINT"                   ";
310 PRINT"                       ";
320 PRINT"            ";
330 PRINT"                         ";
340 PRINT"                  ";
350 PRINT"                   ";
360 PRINT"                ";
370 PRINT"                         ";
380 PRINT"                  ";
390 PRINT"                   ";
400 PRINT"                  ";
410 PRINT"                         ";
420 PRINT"                   ";
430 PRINT"                    ";
440 PRINT"                ";
450 PRINT"                         ";
460 PRINT"                  ";
470 PRINT"                   ";
480 PRINT"                  ";
490 PRINT"                         ";
500 PRINT"                 ";
510 PRINT"                  ";
520 PRINT"               ";
530 PRINT"                           ";
540 PRINT"                            ";
550 PRINT"                         ";
560 PRINT"                           ";
570 PRINT"                            ";
580 PRINT"                         ";
590 PRINT"                           ";
600 PRINT"                            ";
610 PRINT"                         ";
620 PRINT"                            ";
630 PRINT"                            ";
640 PRINT"                        ";
650 PRINT"                            ";
660 PRINT"                            ";
670 PRINT"                        ";
680 PRINT"                            ";
690 PRINT"                            ";
700 PRINT"                        ";
710 PRINT"                            ";
720 PRINT"                            ";
730 PRINT"                        ";
740 PRINT"                            ";
750 PRINT"                            ";
760 PRINT"                        ";
770 PRINT"                            ";
780 PRINT"                            ";
790 PRINT"                        ";
800 PRINT"                            ";
810 PRINT"                            ";
820 PRINT"                        ";
830 PRINT"             ";
840 PRINT"              ";
850 PRINT"              ";
860 PRINT"              ";
870 PRINT"              ";
880 PRINT"           ";
